version: '2'
services:
    ocrgateway-cassandra:
        container_name: ocrgateway-cassandra
        image: cassandra:3.9
        # volumes:
        #     - ~/volumes/jhipster/OcrGateway/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    ocrgateway-cassandra-node:
        image: cassandra:3.9
        links:
            - ocrgateway-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    ocrgateway-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: ocrgateway-cassandra-migration
        links:
            - ocrgateway-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
